# dependabot.yml
#
# Configuration file for Dependabot on the whisthq/brave-browser repository

version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/" # looks for package.json and [package-lock/yarn].lock file in this directory
    schedule:
      interval: "monthly" # runs on the first day of each month
    ignore:
      - dependency-name: "*" # ignore all minor & micro/patch updates for all dependencies
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]
    open-pull-requests-limit: 10
